language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script: 
  - npm publish
branches:
  only:
  - master
before_install:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN